### ISSUE TITLE
Readme out of date...

### ISSUE THREAD

**Issue by LudoTheHUN** [nupic-community/comportex#14]
Hi.

I'm trying to follow through on the readme examples as per here: https://github.com/nupic-community/comportex/wiki/A-sample-workflow-with-the-REPL

I think some names have changed, eg:

```
(core/column-state-freqs (:r0 (:regions-map model)))
```

should now be:

```
(core/column-state-freqs (:rgn-0 (:regions model)))
```

Keep up the good work!

**Comment by floybix** [comment]
Done! And it only took me 11 months...
