### ISSUE TITLE
q_learning_1d demo showing "nth not supported" error in tgt->i arg destructuring

### ISSUE THREAD

**Issue by mrcslws** [nupic-community/comportex#16]
FYI, I think this regressed in a recent comportex commit. I verified that my viz pull requests didn't cause this before I submitted them :). This was working recently.

I'm seeing the error when trying this demo in comportexviz.

**Comment by floybix** [comment]
Thanks, fixed in ffd1c6ebe98dbb3a975dfb1e1a59c4755341427c
