### ISSUE TITLE
Just getting started - cljc files?

### ISSUE THREAD

**Issue by kristianmandrup** [nupic-community/comportex#18]
Hi, I'm just getting started with Clojure and NuPIC via clortex and comportex.

I can't seem to figure out how to get editor support for the `.cljc` files. I'm using Lighttable. 
Any suggestions? Thanks :)

**Comment by floybix** [comment]
Hi

I think you can put this in your user.behaviors

 [:files :lt.objs.files/file-types [{:exts [:cljc], :mime "text/x-clojure",
:tags [:editor.clj :editor.clojure], :name "Cljc"}]]


On Thursday, May 28, 2015, Kristian Mandrup <notifications@github.com>
wrote:

> Hi, I'm just getting started with Clojure and NuPIC via clortex and
> comportex.
>
> I can't seem to figure out how to get editor support for the .cljc files.
> I'm using Lighttable.
> Any suggestions? Thanks :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nupic-community/comportex/issues/18>.
>


-- 
Felix Andrews / 安福立
http://www.neurofractal.org/felix/

**Comment by kristianmandrup** [comment]
Thanks a lot @floybix :)
