### ISSUE TITLE
Any benefit to htm.java again

### ISSUE THREAD

**Issue by berlinbrown** [nupic-community/comportex#50]
Sorry didnt' find a way to communicate this, can we do htm.java? updates?

**Comment by floybix** [comment]
Hello. This project has not been active for several years. This was before the new emphasis on reference frames (cortical grid cells). I have not been following developments much since then.

**Comment by berlinbrown** [comment]
Thanks, where is the work on reference frames, is that an open project?

**Comment by floybix** [comment]
Not sure where they're at with implementations, sorry. Check out Jeff Hawkins' book A Thousand Brains for the general idea.
